name: custom
on: 
 workflow_dispatch:
 push:
    branches:
       - main
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v4

       - name: setup-python
         uses: actions/setup-python@v5
         with:
            python-version: "3.10"

       - name: verify
         run: |
          python --version
          pip --version

       - name: install dependencys
         run: |
           pip install -r requirements.txt
           pip install pytest

       - name: unit test
         run: |
          pytest
          coverage run -m pytest

       - name: coverage xml
         run: |
           coverage xml
           ls -l
        
       - name: Upload Coverage Report
         uses: actions/upload-artifact@v4
         with:
          name: coverage-report
          path: coverage.xml

       - name: pyhton build
         run: |
          pip install build
          python -m build
