name: custom
on: 
 workflow_dispatch:
 push:
    branches:
       - main
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v4

       - name: setup-python
         uses: actions/setup-python@v5
         with:
            python-version: "3.10"

       - name: verify
         run: |
          python --version
          pip --version

       - name: install dependencys
         run: |
           pip install -r requirements.txt
           pip install pytest

       - name: unit test
         run: |
          pytest

       - name: unit test
         run: |
          coverage run -m pytest
          coverage xml
